export const PLAYGROUND_CAPACITY = 40;

export const CAPACITY_WARNING_THRESHOLD = 0.71;
export const CAPACITY_CRITICAL_THRESHOLD = 0.91;

export const CAPACITY_COLOR_AMBER_WARNING = "#E8A87C";
export const CAPACITY_COLOR_CORAL_CRITICAL = "#FF8B83";
